<?php

namespace DoctrineProxies\__CG__\App\models;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ReportRequest extends \App\models\ReportRequest implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportID', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'postID', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportDate', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportStatus', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reason'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportID', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'postID', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportDate', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reportStatus', '' . "\0" . 'App\\models\\ReportRequest' . "\0" . 'reason'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ReportRequest $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getReportID(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getReportID();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportID', []);

        return parent::getReportID();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportID(int $reportID): \App\models\ReportRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportID', [$reportID]);

        return parent::setReportID($reportID);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostID(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostID', []);

        return parent::getPostID();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostID(int $postID): \App\models\ReportRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostID', [$postID]);

        return parent::setPostID($postID);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportDate', []);

        return parent::getReportDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportDate(\DateTimeInterface $reportDate): \App\models\ReportRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportDate', [$reportDate]);

        return parent::setReportDate($reportDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportStatus', []);

        return parent::getReportStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportStatus(string $reportStatus): \App\models\ReportRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportStatus', [$reportStatus]);

        return parent::setReportStatus($reportStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getReason(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReason', []);

        return parent::getReason();
    }

    /**
     * {@inheritDoc}
     */
    public function setReason(int $reason): \App\models\ReportRequest
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReason', [$reason]);

        return parent::setReason($reason);
    }

}
