<?php

namespace DoctrineProxies\__CG__\App\models;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Movie extends \App\models\Movie implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\models\\Movie' . "\0" . 'movieId', '' . "\0" . 'App\\models\\Movie' . "\0" . 'title', '' . "\0" . 'App\\models\\Movie' . "\0" . 'photo', '' . "\0" . 'App\\models\\Movie' . "\0" . 'trailerLink', '' . "\0" . 'App\\models\\Movie' . "\0" . 'duration', '' . "\0" . 'App\\models\\Movie' . "\0" . 'catagory', '' . "\0" . 'App\\models\\Movie' . "\0" . 'releaseDate', '' . "\0" . 'App\\models\\Movie' . "\0" . 'language', '' . "\0" . 'App\\models\\Movie' . "\0" . 'subtitles', '' . "\0" . 'App\\models\\Movie' . "\0" . 'director', '' . "\0" . 'App\\models\\Movie' . "\0" . 'casts', '' . "\0" . 'App\\models\\Movie' . "\0" . 'description', '' . "\0" . 'App\\models\\Movie' . "\0" . 'classification', '' . "\0" . 'App\\models\\Movie' . "\0" . 'status', '' . "\0" . 'App\\models\\Movie' . "\0" . 'schedules'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\models\\Movie' . "\0" . 'movieId', '' . "\0" . 'App\\models\\Movie' . "\0" . 'title', '' . "\0" . 'App\\models\\Movie' . "\0" . 'photo', '' . "\0" . 'App\\models\\Movie' . "\0" . 'trailerLink', '' . "\0" . 'App\\models\\Movie' . "\0" . 'duration', '' . "\0" . 'App\\models\\Movie' . "\0" . 'catagory', '' . "\0" . 'App\\models\\Movie' . "\0" . 'releaseDate', '' . "\0" . 'App\\models\\Movie' . "\0" . 'language', '' . "\0" . 'App\\models\\Movie' . "\0" . 'subtitles', '' . "\0" . 'App\\models\\Movie' . "\0" . 'director', '' . "\0" . 'App\\models\\Movie' . "\0" . 'casts', '' . "\0" . 'App\\models\\Movie' . "\0" . 'description', '' . "\0" . 'App\\models\\Movie' . "\0" . 'classification', '' . "\0" . 'App\\models\\Movie' . "\0" . 'status', '' . "\0" . 'App\\models\\Movie' . "\0" . 'schedules'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Movie $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getMovieId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getMovieId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMovieId', []);

        return parent::getMovieId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto(string $photo): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getTrailerLink(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTrailerLink', []);

        return parent::getTrailerLink();
    }

    /**
     * {@inheritDoc}
     */
    public function setTrailerLink(string $trailerLink): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTrailerLink', [$trailerLink]);

        return parent::setTrailerLink($trailerLink);
    }

    /**
     * {@inheritDoc}
     */
    public function getDuration(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDuration', []);

        return parent::getDuration();
    }

    /**
     * {@inheritDoc}
     */
    public function setDuration(int $duration): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDuration', [$duration]);

        return parent::setDuration($duration);
    }

    /**
     * {@inheritDoc}
     */
    public function getCatagory(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCatagory', []);

        return parent::getCatagory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCatagory(string $catagory): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCatagory', [$catagory]);

        return parent::setCatagory($catagory);
    }

    /**
     * {@inheritDoc}
     */
    public function getReleaseDate(): \DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReleaseDate', []);

        return parent::getReleaseDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setReleaseDate(\DateTimeInterface $releaseDate): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReleaseDate', [$releaseDate]);

        return parent::setReleaseDate($releaseDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getLanguage(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLanguage', []);

        return parent::getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    public function setLanguage(string $language): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLanguage', [$language]);

        return parent::setLanguage($language);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubtitles(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubtitles', []);

        return parent::getSubtitles();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubtitles(string $subtitles): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubtitles', [$subtitles]);

        return parent::setSubtitles($subtitles);
    }

    /**
     * {@inheritDoc}
     */
    public function getDirector(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDirector', []);

        return parent::getDirector();
    }

    /**
     * {@inheritDoc}
     */
    public function setDirector(string $director): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDirector', [$director]);

        return parent::setDirector($director);
    }

    /**
     * {@inheritDoc}
     */
    public function getCasts(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCasts', []);

        return parent::getCasts();
    }

    /**
     * {@inheritDoc}
     */
    public function setCasts(string $casts): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCasts', [$casts]);

        return parent::setCasts($casts);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getClassification(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClassification', []);

        return parent::getClassification();
    }

    /**
     * {@inheritDoc}
     */
    public function setClassification(string $classification): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClassification', [$classification]);

        return parent::setClassification($classification);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(string $status): \App\models\Movie
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

}
